name: main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  HELICONE_API_KEY: ${{ secrets.HELICONE_API_KEY }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  PROMPTLAYER_API_KEY: ${{ secrets.PROMPTLAYER_API_KEY }}

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
    - name: Install dependencies using Poetry
      run: |
        poetry install
    - name: Install neovim
      run: |
        sudo apt install neovim
    - name: Run tests
      run: |
        poetry run pytest

  check-black:
    name: Check Black Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
    - name: Install dependencies using Poetry
      run: |
        poetry install
    - name: Check Black formatting
      run: |
        poetry run black --check .

  check-mypy:
    name: Check MyPy Type Annotations
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
    - name: Install dependencies using Poetry
      run: |
        poetry install
    - name: Run MyPy type check
      run: |
        poetry run mypy .
